ENEMY_RACES = {
    "Human": {"mods": {}, "elemental_res": {}, "elemental_dmg": {}},
    "Goblin": {"mods": {"Dexterity": 2, "Strength": -1, "Constitution": -1},
                "elemental_res": {"earth": 0.8, "light": 0.9},
                "elemental_dmg": {"dark": 1.2}},
    "Orc": {"mods": {"Strength": 3, "Constitution": 1, "Charisma": -2},
            "elemental_res": {"dark": 1.2, "fire": 1.1},
            "elemental_dmg": {"fire": 1.3, "dark": 1.1}},
    "Undead": {"mods": {"Constitution": 3, "Wisdom": -2, "Charisma": -3},
               "elemental_res": {"light": 0.7, "fire": 0.8, "dark": 1.3},
               "elemental_dmg": {"dark": 1.3, "fire": 0.9}},
    "Beast": {"mods": {"Strength": 2, "Dexterity": 1, "Learning": -3},
              "elemental_res": {"earth": 1.2, "wind": 1.1},
              "elemental_dmg": {}},
    "Demon": {"mods": {"Strength": 2, "Charisma": 2, "Wisdom": -1},
              "elemental_res": {"dark": 1.3, "fire": 1.2, "light": 0.6, "water": 0.7},
              "elemental_dmg": {"fire": 1.3, "dark": 1.3}},
    "Construct": {"mods": {"Strength": 2, "Constitution": 4, "Charisma": -5},
                  "elemental_res": {"earth": 1.2, "fire": 1.2, "thunder": 0.7},
                  "elemental_dmg": {"earth": 1.1}},
    "Dragonkin": {"mods": {"Strength": 3, "Constitution": 2, "Learning": -2},
                  "elemental_res": {"fire": 1.2, "thunder": 1.2, "water": 1.1},
                  "elemental_dmg": {"fire": 1.3, "thunder": 1.1}},
    "Fey": {"mods": {"Dexterity": 3, "Charisma": 2, "Strength": -2},
            "elemental_res": {"light": 1.2, "wind": 1.1, "dark": 0.7},
            "elemental_dmg": {"light": 1.3, "wind": 1.2}},
    "Elemental": {"mods": {"Constitution": 3, "Learning": 2, "Dexterity": -1},
                  "elemental_res": {"fire": 1.1, "water": 1.1, "thunder": 1.1, "wind": 1.1, "earth": 1.1, "light": 1.0, "dark": 1.0},
                  "elemental_dmg": {"fire": 1.2, "water": 1.2, "thunder": 1.2, "wind": 1.2, "earth": 1.2}},
    "Giant": {"mods": {"Strength": 4, "Constitution": 2, "Dexterity": -3},
              "elemental_res": {"earth": 1.3, "thunder": 0.8, "wind": 0.7},
              "elemental_dmg": {"earth": 1.3, "fire": 1.1}},
    "Vampire": {"mods": {"Dexterity": 3, "Charisma": 2, "Wisdom": -1, "Constitution": 1},
                "elemental_res": {"dark": 1.2, "light": 0.6, "fire": 0.7},
                "elemental_dmg": {"dark": 1.3, "fire": 0.9}},
    "Lizardfolk": {"mods": {"Constitution": 2, "Strength": 1, "Learning": -1},
                   "elemental_res": {"water": 1.2, "earth": 1.2, "fire": 0.8},
                   "elemental_dmg": {"water": 1.1, "earth": 1.1}},
    "Gnome": {"mods": {"Learning": 2, "Dexterity": 1, "Strength": -2},
              "elemental_res": {"earth": 1.2, "thunder": 1.1},
              "elemental_dmg": {"thunder": 1.3, "earth": 1.1}},
    "Shadow": {"mods": {"Dexterity": 3, "Wisdom": -1, "Constitution": -1},
               "elemental_res": {"dark": 1.3, "light": 0.6},
               "elemental_dmg": {"dark": 1.3}},
    "Clockwork": {"mods": {"Constitution": 3, "Learning": 1, "Charisma": -4},
                  "elemental_res": {"thunder": 0.7, "fire": 1.2},
                  "elemental_dmg": {"thunder": 1.2, "fire": 1.1}},
    "Abomination": {"mods": {"Strength": 4, "Constitution": 3, "Wisdom": -3, "Charisma": -4},
                    "elemental_res": {"dark": 1.2, "light": 0.8, "fire": 1.1, "water": 0.9},
                    "elemental_dmg": {"dark": 1.3, "fire": 1.1}},
}